ios:
  - inputs: [
      'img_front_fisheye', 
      'img_right_fisheye', 
      'img_rear_fisheye', 
      'img_left_fisheye', 
      'img_front_short', 
      'indice_front_fisheye', 
      'indice_right_fisheye', 
      'indice_rear_fisheye', 
      'indice_left_fisheye', 
      'indice_front_short'
      ]
    outputs: ['input.1700']
  - inputs: ['input.1700']
    outputs: ['heatmap', 'reg', 'dim', 'rot']

0:
  conversion:
    quantize: true
    input_layout_overrides:
      "indice_right_fisheye": keep
      "indice_left_fisheye": keep
      "indice_rear_fisheye": keep
      "indice_front_fisheye": keep
      "indice_front_short": keep
    options:
      store_true: ["use_per_channel_quantization"]
      kwargs:
        quantization_overrides: ./config/overrides.json
        
  execute: Null

  dataset:
    data_loader:
      name: NumpyDataLoader
      root: /share/zhangshuo/model_v5/compare/

    data_preprocessor:
      name: NumpyDataPreprocessor

1:
  conversion:
    quantize: true
    output_layout_overrides:
      "heatmap": keep
      "reg": keep
      "dim": keep
      "rot": keep
    options:
      store_true: ["use_per_channel_quantization"]
      kwargs:
        bias_bitwidth: 32
        act_bitwidth: 16
        quantization_overrides: ./config/overrides_s2.json

  execute: Null

  dataset:
    data_loader:
      name: QNNDataLoader
      root: /share/yangcun/370_pod/v5_init/mid/results

    data_preprocessor:
      name: QNNDataPreprocessor
